# backend/pipeline.yaml
# Define o fluxo de trabalho do sistema de agentes.
# Cada chave é o nome de uma tarefa (agente).
# 'next' aponta para a próxima tarefa a ser executada.
# 'stepIndex' corresponde ao índice no array de pipeline da UI.

extraction:
  next: validation
  stepIndex: 0 # Extração de texto

validation:
  next: audit
  stepIndex: 1 # Validação de dados

audit:
  next: classification
  stepIndex: 2 # Auditoria simulada

classification:
  next: analysis
  stepIndex: 3 # Classificação de documentos

analysis:
  next: indexing
  stepIndex: 4 # Análise com IA

indexing:
  next: null # Marca o fim do pipeline
  stepIndex: 5 # Indexação para RAG